<?php
/**
* @file
* A description of what your module does.
*/

use Drupal\Core\Entity\EntityInterface;
use \Drupal\node\NodeInterface;

/**
 * Implements hook_mail().
 */
function jixmailer_mail($key, &$message, $params){
    $options = array(
        'langcode' => $message['langcode'],
    );

    switch ($key){
        case 'job_insert':
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            $message['subject'] = t('Un nouveau job créé: @title', array('@title' => $params['subject']));
            $message['body'][] = $params['message'];
            $message['options'] = [];
            if (isset($params['options']) && !empty($params['options'])){
                foreach ($params['options'] as $key => $value){
                    $message['options'][$key] = $value;
                }
            }
            break;
        case 'job_published':
            $message['from'] = Drupal::config('system.site')
                    ->get('name') . ' <' . Drupal::config('system.site')->get('mail') . '>';
            $message['subject'] = t('Votre offre d\'emploi chez @site est publié', [
                '@site' => Drupal::config('system.site')->get('name'),
            ], $options);
            $message['body'][] = $params['message'];
            break;
        case 'job_created':
            $message['from'] = Drupal::config('system.site')
                ->get('name') . ' <' . Drupal::config('system.site')->get('mail') . '>';
            $message['subject'] = t('Nouvelle annonce soumise sur @site', [
              '@site' => Drupal::config('system.site')->get('name'),
            ], $options);
            $message['body'][] = $params['message'];
            break;
    }
}