<?php
/**
* @file
* A description of what your module does.
*/

use Drupal\Core\Entity\EntityInterface;
use \Drupal\node\NodeInterface;
use \Drupal\Core\Entity\t;

/**
 * Implements hook_mail().
 */
function jixmailer_mail($key, &$message, $params){
    $options = array(
        'langcode' => $message['langcode'],
    );

    switch ($key){
        case 'node_insert':
            $message['from'] = Drupal::config('system.site')->get('mail');
            $message['subject'] = t('Une offre a été créée: @title', array('@title' => $params['node_title']), $options);
            $message['body'][] = $params['message'];
            break;
    }

}

/**
 * Implements hook_entity_insert().
 */
function jixmailer_entity_insert(EntityInterface $entity){
    if (!$entity instanceof NodeInterface || $entity->bundle() !== 'job'){
        return;
    }

    $mailManager = Drupal::service('plugin.manager.mail');
    $module = `jixmailer`;
    $key = 'node_insert';
    $to = $entity->get('field_job_contact_email')->getValue();
    $params['message'] = $entity->getTitle();
    $params['node_title'] = $entity->label();
    $langcode = Drupal::languageManager()->getDefaultLanguage()->getName();
    $send = true;
    $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
    kint($to);
    die();
    if ($result['result'] !== true){
        $message = t('Error sending email to @email after creation of job nid: @id', array('@email' => $to, '@id' => $entity->id()));
        drupal_set_message($message, 'error');
        Drupal::logger('jixmailer')->error($message);
        return;
    }
    $message = t('Email notification sent to @email after creation of job nid: @id', array('@email' => $to, '@id' => $entity->id()));
    drupal_set_message($message, 'status');
    Drupal::logger('jixmailer')->notice($message);
}